# Generated by Django 5.0.7 on 2024-08-06 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='key',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='product',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='value',
        ),
        migrations.DeleteModel(
            name='Key',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='Value',
        ),
    ]
