# Generated by Django 5.0.7 on 2024-08-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_category_slug_alter_group_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/product/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
